name: Version

on:
    push:
        branches:
            - 'main'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: git config
              run: |
                  git config user.name "${GITHUB_ACTOR}"
                  git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - run: npm ci
            - run: npx nx version topic-inspector --push --baseBranch main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
